In [3]:
import random
random.randint(1,3)

1

In [4]:
import numpy as np
mat=np.matrix("1,2,3,4;2,3,4,5;3,4,5,6;6,7,8,9")

In [5]:
mat

matrix([[1, 2, 3, 4],
        [2, 3, 4, 5],
        [3, 4, 5, 6],
        [6, 7, 8, 9]])

In [6]:
np.linalg.det(mat)

0.0

the matrix with det 0 are singular matrix and has no inverse 

In [7]:
np.linalg.matrix_rank(mat)

2

In [8]:
a=np.matrix("1,8,9,3;12,6,8,4;5,8,9,7;13,7,5,4")

In [9]:
a

matrix([[ 1,  8,  9,  3],
        [12,  6,  8,  4],
        [ 5,  8,  9,  7],
        [13,  7,  5,  4]])

In [10]:
np.linalg.det(a)

-1304.0000000000002

In [11]:
np.linalg.inv(a)

matrix([[-0.03834356,  0.07055215, -0.04141104,  0.03067485],
        [ 0.16257669, -0.2791411 , -0.06441718,  0.26993865],
        [ 0.04141104,  0.26380368, -0.03527607, -0.23312883],
        [-0.21165644, -0.07055215,  0.29141104, -0.03067485]])

In [12]:
np.linalg.matrix_rank(a)

4

##### consider a sysytem of equation 
3x+y+2z=2
3x+2y+5z=-1
6x+7y+8z=3


### AX=b
A=[[2,1,2],[3,2,5],[6,7,8]]

X=[[x],[y],[z]]

b=[[2],[-1],[3]]


X=1/A.b

In [13]:
A=np.matrix("2,1,2;3,2,5;6,7,8")
b=np.matrix("2;-1;3")

In [14]:
X=np.linalg.inv(A)*b

In [15]:
X


matrix([[ 2.92857143],
        [ 0.28571429],
        [-2.07142857]])

hence, x=2.93
        y=0.28
        z=-2.07

In [16]:
np.linalg.solve(A,b)

matrix([[ 2.92857143],
        [ 0.28571429],
        [-2.07142857]])

the same can be obtained directly withsolve 

In [17]:
a

matrix([[ 1,  8,  9,  3],
        [12,  6,  8,  4],
        [ 5,  8,  9,  7],
        [13,  7,  5,  4]])

In [18]:
np.matrix(a).transpose()

matrix([[ 1, 12,  5, 13],
        [ 8,  6,  8,  7],
        [ 9,  8,  9,  5],
        [ 3,  4,  7,  4]])

In [19]:
a.transpose()

matrix([[ 1, 12,  5, 13],
        [ 8,  6,  8,  7],
        [ 9,  8,  9,  5],
        [ 3,  4,  7,  4]])

###### SET


In [20]:
age={23,44,56,23}


In [21]:
age

{23, 44, 56}

no duplicate value

In [22]:
age.add(45)

In [23]:
age

{23, 44, 45, 56}

In [24]:
age.discard(56)

In [25]:
age


{23, 44, 45}

In [26]:
age.clear()

In [27]:
age

set()

In [28]:
type(age)

set

In [29]:
del age

In [30]:
age

NameError: name 'age' is not defined

In [31]:
age1={23,26,34,56,53,42}
age2={45,34,32,25,23}

In [32]:
age1.union(age2)

{23, 25, 26, 32, 34, 42, 45, 53, 56}

In [33]:
age1.intersection(age2)

{23, 34}

In [34]:
age1.difference(age2)

{26, 42, 53, 56}

In [35]:
age1.symmetric_difference(age2)

{25, 26, 32, 42, 45, 53, 56}

##### READING FILES
comma seperated value (.csv)file
spreadsheet format

In [36]:
import os

In [37]:
import pandas as pd

In [38]:
os. chdir("C:\Users\kpraw\small_project")

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<ipython-input-38-c3c3b2028e1e>, line 1)

In [47]:
reading=pd.read_csv(r"C:\Users\kpraw\small_project\oo.csv",encoding='utf-8',index_col=0,na_values=["??","##"])

In [48]:
reading


i am using   python to read the file    
hyy there                                                             
thanks to youtube and nptel           NaN                      NaN NaN

In [ ]:
readig_xsls=pd.read_excel("ioo.xlsx",sheet_name='Iris_data')

In [ ]:
data=pd.read_table("gjg.txt",sep='\t')
data=pd.read_table("gjg.txt",delimeter='\t')
